modLoader = "javafml"
loaderVersion = "[${loader_major},)"
issueTrackerURL = "https://github.com/Lemonochrme/ImmersiveTrains/issues"
license = "GPL-3.0-only"

[[mixins]]
config = "immersive_trains.mixins.json"

[[mods]]
modId = "immersive_trains"
version = "${version}"
displayName = "Immersive Trains"
displayURL = "https://github.com/Lemonochrme/ImmersiveTrains"
authors = "Lemonochrme"
description = "A bunch of vanilla-friendly trains to travel, transport, and explore!"
logoFile = "icon.png"
# TODO: Replace with train-themed icon once train entities are implemented
itemIcon = "immersive_trains:biplane"

[[dependencies.immersive_trains]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersive_trains]]
modId = "neoforge"
mandatory = true
versionRange = "[${loader_major},)"
ordering = "NONE"
side = "BOTH"